# -*- mode: python ; coding: utf-8 -*-

import os

# 分析配置
a = Analysis(
    ['app\\main.py'],
    pathex=[],
    binaries=[],
    datas=[('app\\resources', 'resources')],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PIL',
        'PIL.Image',
        'requests',
        'numpy',
        'imagehash'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除不必要的库，减少体积
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
        'spyder',
        'PyQt6.QtWebEngine',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtNetwork',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        'tkinter',
        'test',
        'tests',
        'unittest',
        'pytest',
        'setuptools',
        'wheel',
        'pip',
        'debugpy',
        'jedi',
        'parso',
        'pylint',
        'flake8',
        'black',
        'sphinx',
        'docutils',
        'numpy.testing',
        'scipy.testing',
        'pandas.testing',
        'matplotlib.testing',
        'PyQt6.QtTest',
        'PyQt6.QtDesigner',
        'PyQt6.QtHelp',
        'PyQt6.QtSql',
        'PyQt6.QtXml',
        'PyQt6.QtSvg',
        'PyQt6.QtOpenGL',
        'PyQt6.QtBluetooth',
        'PyQt6.QtPositioning',
        'PyQt6.QtQuick',
        'PyQt6.QtQuickWidgets',
        'PyQt6.QtSensors',
        'PyQt6.QtSerialPort',
        'PyQt6.QtWebSockets',
        'PyQt6.QtNfc',
        'PyQt6.QtRemoteObjects',
        'PyQt6.Qt3DCore',
        'PyQt6.Qt3DRender',
        'PyQt6.Qt3DInput',
        'PyQt6.Qt3DLogic',
        'PyQt6.Qt3DExtras',
        'PyQt6.QtCharts',
        'PyQt6.QtDataVisualization',
        'PyQt6.QtGamepad',
        'PyQt6.QtLocation',
        'PyQt6.QtPrintSupport',
        'PyQt6.QtPurchasing',
        'PyQt6.QtScxml',
        'PyQt6.QtSpeech',
        'PyQt6.QtUiTools',
        'PyQt6.QtWinExtras',
        'PyQt6.QtAxContainer',
        'PyQt6.QtQml',
        'PyQt6.QtQuick3D',
        'PyQt6.QtQuick3DRuntimeRender',
        'PyQt6.QtQuick3DUtils',
        'PyQt6.QtQuickTimeline',
        'PyQt6.QtQuickWidgets',
        'PyQt6.QtShaderTools',
        'PyQt6.QtVirtualKeyboard',
        'PyQt6.Qt6Widgets'
    ],
    noarchive=False,
    optimize=0,
)

# 创建可执行文件
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ImageTrim',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app\\resources\\icons\\imagetrim.ico'],
)